function [fitresult, gof] = figure_mean_cost(mean_cost)
%CREATEFIT(MEAN_COST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: mean_cost
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Apr-2024 10:23:17


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], mean_cost );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.Robust = 'LAR';
opts.StartPoint = [0.000342290147466813 -2.35914533054742 0.0140165507940272 -0.0121368035323544];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
axis tight
h = plot( fitresult, xData, yData, 'predobs', 0.9 );
legend( h, 'mean_cost', 'Trend', 'Lower bounds (90%)', 'Upper bounds (90%)', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'mean_cost', 'Interpreter', 'none' );
grid on


